[package]
name = "imageToText"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.18.0"
clap = { version = "4.4.18", features = ["derive"] }
crossterm = "0.28.1"
flume = "0.11.0"
image = "0.24.8"
wgpu = "22.1.0"
